### ISSUE TITLE
Readme snippet missing `addPlugin`

### ISSUE THREAD

**Issue by mikewesthad** [jdlubrano/datamaps-zoomto-plugin#6]
I stumbled across your plugin earlier, which saved me from quite a few headaches due to me messing up the lat/long => svg translate logic in my code. Thanks for sharing it! I'm new to datamaps, so I might have missed something, but do the snippets in the readme work as is? I think they might be missing `map.addPlugin`, at least when working with the latest version of datamaps (with webpack).

```js
import Datamap from "datamaps";
import zoomto from "datamaps-zoomto";
const map = new Datamap({ /* ... */ });
map.addPlugin("zoomto", zoomto); // <- this
map.zoomto({ /* ... */ });
```

**Comment by jdlubrano** [comment]
Thanks for reaching out.  I haven't looked at this plugin in a while; certainly not with the most recent version of Webpack.  I will look into this and see what I learn.

**Comment by jdlubrano** [comment]
@mikewesthad 

Thank you for bringing this to my attention.  I don't even know if I ever got the `import` syntax to work through my own efforts, so my previous recommendation would have been to use `require` to pull in this plugin as a dependency.  Your snippet does, however, appear to fix any issues that I had using `import`, so I will add your example to the README.

**Comment by mikewesthad** [comment]
👍 thanks!
